#!/bin/bash

sudo modprobe batman-adv
sudo ip link set up dev eth0
sudo ip link set mtu 1532 dev wlan0
sudo iwconfig wlan0 mode ad-hoc essid ege-mesh ap 02:12:34:56:78:9A channel 1
sudo batctl if add wlan0
sudo ip link set up dev wlan0
sudo ip link set up dev bat0
sudo avahi-autoipd -D bat0

